trigger:
- RFQ_DEMO_BRANCH
 
pool:
  vmImage: 'windows-latest'
 
variables:
  pythonVersion: '3.11.5'
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true
 
- script: |
    pip install -r backend/requirements.txt
    python backend/run_waitres_server.py
  displayName: 'Install Python dependencies'
 
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
 
- script: |
    npm install --force
    npm run build
  displayName: 'npm install and build'
 

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
