trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  pythonVersion: '3.11'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install --force
    npm run build
  displayName: 'npm install and build'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r backend/requirements.txt
  displayName: 'Install Python dependencies'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '09a2a035-e105-4383-970b-901b13e3cf62'
    appType: 'webApp'
    WebAppName: 'rfqsummarizer'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*'
  displayName: 'Deploy to Azure App Service'